In [1]:
!pip install numpy


Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [5]:
python_list = [1,2,3,4,5]
print(python_list)
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)
# it takes less space

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [14]:
# 2d array
import numpy as np
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
# multi dimensional array
# matrix
matrix = np.array([[2,3,4],
                  [5,6,7]])    
print(matrix)

[[2 3 4]
 [5 6 7]]


In [21]:
# creating array in python list
#np.array[el1,l2,l3,l4]
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [24]:
# creating arrays with defaults
#np.zeros(shape) (3) for 1d,(3,3) for 2d
import numpy as np
arr = np.zeros(3)
print(arr)

[0. 0. 0.]


In [27]:
# ones(shape)
import numpy as np
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# full function
# full(shape,value)
import numpy as np
filled_arr = np.full((3,3),8)
print(filled_arr)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [33]:
# creating sequences in numpy
# used arange function same as range diff.is that it returns numpy function
# arange (start,stop,step)
import numpy as np
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [34]:
# creating identity matrix - ones at the diagonal and else 0
#eye(shape)
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
#numpy array properties and operations
# shape
import numpy as np
arr_2d =np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d.shape)

(3, 3)


In [5]:
#to find no. of attributes in an array
arr_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d.size)

9


In [10]:
#ndim - no.of dimensions in an array
import numpy as np
arr_1d = np.array([1,2,3])
arr_2d =np.array([[4,5,6],[8,9,7]])# 2 square brackets for 2d
arr_3d =np.array([[[1,2],[3,4],[5,6],[7,8]]])#3 square brackets for 3d
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


In [11]:
#dtype - used to check datatype
arr =np.array([3,4.5,8,9])
print(arr.dtype)

float64


In [14]:
# .astype(new type) to convert to different data type
arr = np.array([5.6])
print(arr.dtype)
int_arr = arr.astype(int)
print(int_arr)
print(int_arr.dtype)

float64
[5]
int32


In [15]:
#aggregation function
arr = np.array([3,4,5,6])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))

18
4.5
3
6
1.25


In [2]:
# indexing 
# array[index]#1d array
#array[row,column] #2nd
import numpy as np
arr = np.array([10,20,30,30,50])
print(arr[0])# first element
print(arr[-1])A# last element

10
50


In [11]:
# slicing
#[start,stop,step]
# arr[start:end],start to end -1
# negative step,-1reverse
arr = np.array([10,20,30,40,50])
print(arr[0:4:2])
print(arr[1:5])# index 1 to 4
print(arr[:4])# index 0 to 3
print(arr[::2])# every 2nd element
print(arr[::-1])# reverse the array

[10 30]
[20 30 40 50]
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]


In [12]:
# fancy indexing -selecting multiple elements at once
arr = np.array([10,20,30,40,50])
print(arr[[0,3,4]])

[10 40 50]


In [15]:
# filtering data- boolean masking
arr = np.array([10,20,30,40,50])
print(arr[arr<50])

[10 20 30 40]


In [18]:
# reshaping & manipulating arrays
"""
reshaping = changing the dimension without changing the array
1d -2d,2d - 3d ,it does not create copy ,it ceate a view and it affect our array
reshape(rows,columns)specify new shape if dimension match
arr.reshape()
"""
arr = np.array([1,2,3,4,5,6])
reshape_arr = arr.reshape(3,2)
print(reshape_arr)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
#flattering array -change multidimensional to 1d array
# .ravel() - view
# .flatten() - copy'
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [42]:
"""
np.insert(array,index,value,axis = None)
axis is none thrn it is flatten - 1d array
axis is 0 ,1 then it is in 2d array
axis - 0 then row wise
axis -1 then column wise insert data
"""
arr = np.array([10,20,30,40,50])
new_arr = np.insert(arr,3,70,axis = None)
print(new_arr)
arr_2d = np.array([[10,20],[30,40]])
new_arr2d = np.insert(arr_2d,2,70,axis =1)
print(new_arr2d)
new_arr2c = np.insert(arr_2d,1,70,axis =0)
print(new_arr2c)


[10 20 30 70 40 50]
[[10 20 70]
 [30 40 70]]
[[10 20]
 [70 70]
 [30 40]]


In [39]:
# append - add the element in the end
arr = np.array([10,20,30,40,50])
new_arr = np.append(arr,[40,50,60])
print(new_arr)

[10 20 30 40 50 40 50 60]


In [48]:
# concatenation - join different array
#np.concatenate((array1,array2),axis = 0,1)
arr1 = np.array([[10,20,30],[40,50,60]])
print(arr1)
arr2 = np.array([[50,60,70],[80,90,100]])
print(arr2)
new_arr = np.concatenate((arr1,arr2),axis =0)
print(new_arr)

[[10 20 30]
 [40 50 60]]
[[ 50  60  70]
 [ 80  90 100]]
[[ 10  20  30]
 [ 40  50  60]
 [ 50  60  70]
 [ 80  90 100]]


In [52]:
# removing element from array
# np.delete(array,index,axis =None)
arr1 = np.array([[10,20,30],[40,50,60]])
new_arr = np.delete(arr1,2,axis =1)
print(new_arr)

[[10 20]
 [40 50]]


In [56]:
#Stacking - combining vertically and horizentally
# vstack() - row wise
# hstack() - column wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("row wise")
print(np.vstack((arr1,arr2)))
print("column wise ")
print(np.hstack((arr1,arr2)))

row wise
[[1 2 3]
 [4 5 6]]
column wise 
[1 2 3 4 5 6]


In [62]:
# splitting
# np.hsplit()
# np.vsplit()
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


In [75]:
# using loop
prices =[100,200,300]
discount = 10  # 10% discount 
final_prices = []
for price in prices:
    final_price = price -(price*discount/100)
    final_prices.append(final_price)
print(final_prices)

[90.0, 180.0, 270.0]


In [63]:
# broadcasting and vectorization
"""
broadcasting - applying multiple mathematical opertions without using loop
"""
import numpy as np
prices = np.array([100,200,300])
discount = 10
final_prices = prices -(prices *discount/100)
print(final_prices)

[ 90. 180. 270.]


In [ ]:
# how array should arrays of different shapes
# matching dimension
# expanding single element - array_1[1,2,3] +array_2[10] = new_arr[11,12,13]
# incompatible shape -[1,2,3]+[1,2] = shows error


In [76]:
import numpy as np
arr = np.array([100,200,300])
result = arr*2
print(result)

[200 400 600]


In [80]:
matrix = np.array([[1,2,3],[4,5,6]])   # 2x3 matrix
vector = np.array([10,20,30])   #1d array  
result = (matrix*vector)
print(result)

[[ 10  40  90]
 [ 40 100 180]]


In [83]:
# incompatible shape
"""
arr1 = np.array([1,2,3],[4,5,6])# shape(2,3)
arr2 = np.array([1,2])# shape[2 elements]
result = (arr1 + arr2)
print(result)
"""
# throw an error because both has different shapes 

'\narr1 = np.array([1,2,3],[4,5,6])# shape(2,3)\narr2 = np.array([1,2])# shape[2 elements]\nresult = (arr1 + arr2)\nprint(result)\n'

In [84]:
# vectorixation - to perform faster calulation without using loops
import numpy as np
arr = np.array([100,200,300])
result = arr*3
print(result)

[300 600 900]


In [87]:
#handling missing values in numpy
# isnan function(array)
import numpy as np
arr = np.array([1,2,np.nan,4,5,np.nan,6,7])
print(np.isnan(arr))
# where the output is true value is missing

[False False  True False False  True False False]


In [ ]:
"""
can we compare np.nan values 
no we can't directly """

In [89]:
# nan to num - np.nan_to_num(array,nan-value ,default =0)
arr = np.array([2,3,4,5,6,np.nan,7,np.nan])
print(np.nan_to_num(arr,nan = 100))
print(np.nan_to_num(arr))


[  2.   3.   4.   5.   6. 100.   7. 100.]
[2. 3. 4. 5. 6. 0. 7. 0.]


In [93]:
# to handle infinite values
#np.isinf()
# posinf = positive infinity
# neginf = negative infinity
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))
cleaned_arr = np.nan_to_num(arr,posinf=1000,neginf=1000)
print(cleaned_arr) 


[False False  True False  True False]
[   1.    2. 1000.    4. 1000.    6.]
